### ISSUE TITLE
Is this code working? which hailort version are you using?

### ISSUE THREAD

**Issue by bash-sanka1p** [acredsfan/autonomous_mower_ai_addon#1]
Hi, 
Im also trying to understand this whole HAILO with pi interface. Came across your code is it really working?
tried to run the code step by step with my own model but i got error after configuring the network.
im not able to understande this hailort fully. the closest i have got it to working is using this good script by AlbertaBeef linked [here](https://github.com/AlbertaBeef/blaze_app_python/blob/main/blaze_hailo/hailo_inference.py)
He used mediapipe models, by im using yolov8. 
it did returned me the output but that output only contains two information namely bboxes and confidence score. it did not return the class id.
i saw you are using yolov8 as well but i could not get your code working on my system with custom model.

im  using hailort==v4.18.0
were you using the same?

sorry i dont create issues that much so i have no idea about its format.

**Comment by acredsfan** [comment]
Hi,

I appreciate you taking the time to reach out.  This repository is a kind of offshoot from the the autonomous_mower project I'm working on, which has been my main focus with my free time.  The code here is very much just a framework to get me started and I haven't been able to test it much yet.  I'm currently working on training a yolov8 model with obstacle detection/identification as well as surface identification (so the mower knows if it's on grass or some other surface like a sidewalk, flower bed, or driveway).  I will be updating this in the coming days but as of right now it's not fully working.  Feel free to follow along or contribute if you'd like, I'll try to update documentation and other pieces of this as I can.

Thanks!

**Comment by bash-sanka1p** [comment]
Hello,
I solved my issue following [this](https://support.deepviewml.com/hc/en-us/articles/25632426283149-Hailo-Inference)
This contains the postinference step i required.
